#@TYPE: Machine
#@NAME: Radxa Rock 5A
#@DESCRIPTION: ROCK5 is the 5th generation of SBC designed by Radxa.
#https://docs.radxa.com/en/rock5/rock5a

require conf/machine/include/rk3588s.inc

#
# Kernel
#
#PREFERRED_PROVIDER_virtual/dtb = "devicetree-radxa"
#EXTERNAL_KERNEL_DEVICETREE = "bulleseye.dtb"

KERNEL_DEVICETREE = "rockchip/rk3588s-rock-5a.dtb"
MACHINE_EXTRA_RRECOMMENDS += "kernel-modules"
PREFERRED_PROVIDER_virtual/kernel = "linux-radxa"

SERIAL_CONSOLES = "1500000;ttyFIQ0"
KERNEL_IMAGETYPE = "Image"

KBUILD_DEFCONFIG = "rockchip_linux_defconfig"


#
# U-boot
#
UBOOT_MACHINE = "rock5a-rk3588s_defconfig"
PREFERRED_PROVIDER_virtual/bootloader = "u-boot-rockchip"
SPL_BINARY = "idbloader.img"
UBOOT_SUFFIX ?= "itb"


#
# Image
#
# Use systemd init manager
INIT_MANAGER = "systemd"

# No X11 rubbish
DISTRO_FEATURES:remove = "x11"

# Build a wic image
IMAGE_FSTYPES += "wic"
WKS_FILE = "image.wks"
ROOT_PARTUUID = "e9852d44-6984-472c-8845-9ad2ba36bfd2"
WICVARS:append = " SPL_BINARY UBOOT_SUFFIX ROOT_PARTUUID"

PREFERRED_PROVIDER_virtual/egl ?= "rockchip-libmali"
PREFERRED_PROVIDER_virtual/libgles1 ?= "rockchip-libmali"
PREFERRED_PROVIDER_virtual/libgles2 ?= "rockchip-libmali"
PREFERRED_PROVIDER_virtual/libgles3 ?= "rockchip-libmali"
PREFERRED_PROVIDER_virtual/libopencl ?= "rockchip-libmali"
PREFERRED_PROVIDER_virtual/libgbm ?= "rockchip-libmali"